export class EmployeeData {

  constructor(
    //  public Name: string,
    //  public empType: string,
    //  public companyType: string,
    //  public designation: string,
    //  public Division: string,
    //  public department: string,
    //  public location: string,
    //  public floor: number,
    //  public telephone: number,
    //  public mobile: string,
    //  public retirementDate: Date,
    //  public hodEC: string,
    //  public hodName: string,
    //  public dirEC: string,
    //  public dirName: string,
    public Name: string,
    public Employee_type: string,
    public Company_Name: string,
    public Designation: string,
    public Division: string,
    public Department : string,
    public Location : string,
    public floor : number,
    public Telephone : number,
    public Mobile: number,
    public Retirement_date : Date,
    public HOD_EC_code : string,
    public HOD_Name : string,
    public Director_code : number,
    public Director_Name : string
    ) {}
}
